name: Publish Updates
on:
  push:
    branches: [ 'master' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Updates
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '20'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Setup bundler cache
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Update apt repo sources
        run: sudo apt-get update -y
      - name: Install xmllint
        run: sudo apt-get install libxml2-utils
      - name: Install ruby gem dependencies with bundler
        run: |
          gem install bundler -v 2.4.22
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run type data migrations to create gameobj-data.xml
        run: bin/migrate
      - name: Release updates to Tillmen's Lich repository
        env:
          AUTHOR: ${{ secrets.repo_author }}
          PASSWORD: ${{ secrets.repo_password }}
          TRAVIS_COMMIT: ${{ github.sha }}
          TRAVIS_COMMIT_RANGE: ${{ github.event.before }}..${{ github.sha }}
        run: bin/repo
