name: Publish Updates
on:
  push:
    branches: [ 'master' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Updates
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '20'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - name: Update apt repo sources
        run: sudo apt-get update -y
      - name: Install xmllint
        run: sudo apt-get install libxml2-utils
      - name: Run type data migrations to create gameobj-data.xml
        run: bin/migrate
      - name: Release updates to Tillmen's Lich repository
        env:
          AUTHOR: ${{ secrets.repo_author }}
          PASSWORD: ${{ secrets.repo_password }}
          TRAVIS_COMMIT: ${{ github.sha }}
          TRAVIS_COMMIT_RANGE: ${{ github.event.before }}..${{ github.sha }}
        run: bin/repo
