name: Valid Ruby Syntax
on:
  push:
    branches:
      - master
    paths:
      - 'scripts/**'
      - 'type_data/migrations/**'
                  
  pull_request:
    paths:
      - 'scripts/**'
      - 'type_data/migrations/**'

jobs:
  check_syntax:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: 'gtk:vscode:profanity'
    strategy:
      matrix:
        ruby: ['4.0']
    name: Run tests on Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.2
        with:
          fetch-depth: 0
          
      - name: Get changed files
        id: changed-files
        uses: step-security/changed-files@95b56dadb92a30ca9036f16423fd3c088a71ee94 # v46.0.5
        with:
          files: |
            **/*.lic
            **/*.rb

      - uses: ruby/setup-ruby@708024e6c902387ab41de36e1669e43b5ee7085e # v1.283.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          
      - name: Run Ruby syntax check on changed scripts
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            ruby -c $file
          done
